"""add interview schedule

Revision ID: 40866d6d1d3b
Revises: 86ca46985311
Create Date: 2026-07-15 03:25:51.171955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40866d6d1d3b'
down_revision = '86ca46985311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('interview_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('interview_mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('interview_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('interview_link')
        batch_op.drop_column('interview_mode')
        batch_op.drop_column('interview_time')
        batch_op.drop_column('interview_date')

    # ### end Alembic commands ###
