"""add job status and eligibility fields

Revision ID: 86ca46985311
Revises: d6987246cfac
Create Date: 2026-07-13 17:48:00.599067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ca46985311'
down_revision = 'd6987246cfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eligibility_branch', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('eligibility_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('reason')
        batch_op.drop_column('status')
        batch_op.drop_column('eligibility_year')
        batch_op.drop_column('eligibility_branch')

    # ### end Alembic commands ###
